# .github/workflows/release.yaml
on: release
name: Build Release
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "goinitVTAG"
        replace: ${{ env.RELEASE_VERSION }}
        include: "main.go"
    - name: compile and release
      uses: h4ux/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: linux
        EXTRA_FILES: "LICENSE.md"
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "goinitVTAG"
        replace: ${{ env.RELEASE_VERSION }}
        include: "main.go"
    - name: compile and release
      uses: h4ux/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: linux
        EXTRA_FILES: "LICENSE.md"
  release-linux-arm:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "goinitVTAG"
        replace: ${{ env.RELEASE_VERSION }}
        include: "main.go"
    - name: compile and release
      uses: h4ux/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "arm"
        GOOS: linux
        EXTRA_FILES: "LICENSE.md"
  release-linux-arm64:
    name: release linux/arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "goinitVTAG"
        replace: ${{ env.RELEASE_VERSION }}
        include: "main.go"
    - name: compile and release
      uses: h4ux/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: arm64
        GOOS: linux
        EXTRA_FILES: "LICENSE.md"
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "goinitVTAG"
        replace: ${{ env.RELEASE_VERSION }}
        include: "main.go"
    - name: compile and release
      uses: h4ux/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: darwin
        EXTRA_FILES: "LICENSE.md"
  release-darwin-386:
    name: release darwin/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "goinitVTAG"
        replace: ${{ env.RELEASE_VERSION }}
        include: "main.go"
    - name: compile and release
      uses: h4ux/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: 386
        GOOS: darwin
        EXTRA_FILES: "LICENSE.md"